build:
  image: bjodah/bjodahimgdev:latest
  commands:
    - conda config --add channels bjodah
    - ./scripts/ci.sh sym
    - ./scripts/render_examples.sh
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: sym
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
