build:
  image: bjodah/bjodahimg:latest
  commands:
    # - wget --quiet https://repo.continuum.io/miniconda/Miniconda2-3.19.0-Linux-x86_64.sh -O miniconda2.sh 
    # - wget --quiet http://hera.physchem.kth.se/~repo/628f158791daf7d634fb6894045a6be1/Miniconda2-3.19.0-Linux-x86_64.sh -O miniconda2.sh 
    # - echo 628f158791daf7d634fb6894045a6be1 miniconda2.sh | md5sum -c --
    # - bash miniconda2.sh -b -p /opt/miniconda2
    - export PATH=/opt/miniconda2/bin:$PATH
    - conda config --add channels bjodah
    - conda config --set always_yes yes
    - conda config --set changeps1 no
    - ./scripts/ci.sh sym
    - (cd examples/; ipython2 nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: sym
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
