pipeline:
  build:
    image: bjodah/bjodahimg20dot:2.1.1.2
    environment:
      - CC=gcc-10
      - CXX=g++-10
    commands:
      - python3 -m pip install --install-option="--symengine-dir=/opt/symengine-46090cf-rel" https://github.com/symengine/symengine.py/archive/6ea7333ff2986524f8ca4bb89e42319e8ec154f1.tar.gz
      - SYM_STRICT_TESTING=1 ./scripts/ci.sh sym
      - ./scripts/prepare_deploy.sh

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]
    port: 22
    user: sym
    secrets: [ rsync_key ]  # secret only set from event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
