pipeline:
  build:
    image: bjodah/bjodahimg20dot:2.1.1.2
    environment:
      - CC=gcc-10
      - CXX=g++-10
      - SymEngine_DIR=/opt/symengine-46090cf-rel
    commands:
      - python3 -m pip install https://github.com/symengine/symengine.py/archive/62a0d89b5b9ad00814c5cd2f72e697aa1c21dccd.tar.gz
      - SYM_STRICT_TESTING=1 ./scripts/ci.sh sym
      - ./scripts/prepare_deploy.sh

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]
    port: 22
    user: sym
    secrets: [ rsync_key ]  # secret only set from event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
