build:
  image: bjodah/bjodahimg20dev:v1.0.3
  commands:
    - SYM_STRICT_TESTING=1 ./scripts/ci.sh sym
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: sym
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
