when:
  - event: [push]

steps:
  - name: build
    image: bjodah/bjodahimg20dot:21.8.a
    environment:
      - CC=gcc-11
      - CXX=g++-11
#      - SymEngine_DIR=/opt/symengine-24c9d19-rel
    commands:
#      - python3 -m pip install https://github.com/symengine/symengine.py/archive/62a0d89b5b9ad00814c5cd2f72e697aa1c21dccd.tar.gz
      - SYM_STRICT_TESTING=1 ./scripts/ci.sh sym
      - ./scripts/prepare_deploy.sh
