{% set name = "sym" %}
{% set version = "0.2.0.git" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - {{ name }}

  requires:
    - pytest
    - numpy
    - sympy
    - symcxx
    - python-symengine
    - pysym

  commands:
    - py.test --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD
  license_file: LICENSE
  summary: 'Unified wrapper to symbolic manipulation libraries in Python.'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
